MyChoice/Models/AnimalModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyChoice.Models
{
    public class AnimalModel
    {
        public string name { get; set; }
        //critical, endangered, near threatened, vulnerable, least threatened
        public string classification { get; set; } = "critical";
        public double donation { get; set; } = 100.00;
    }
}

MyChoice/Controllers/AnimalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyChoice.Controllers
{
    public class AnimalsController : Controller
    {
        // GET: Animals
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(string selCategory)
        {
            var endangeredType = HttpUtility.HtmlEncode(selCategory);
            var viewName = "";
            switch (endangeredType)
            {
                case "Critical":
                    viewName= "Critical";
                    break;
                case "Endangered":
                    viewName = "Endangered";
                    break;
                case "Near Threatened":
                    viewName = "nearThreatened";
                    break;
                case "Vulnerable":
                    viewName = "Vulnerable";
                    break;
                default:
                    viewName = "LeastThreatened";
                    break;
            }
            return View(viewName);
        }
       
        [HttpPost]
        public ActionResult AnimalAdoptionForm(string name, string donation)
        {
            if (name == "")
                name = "animal";
            ViewBag.message = "Thank you for your wonderful donation of " + donation;
            ViewBag.message += ".  The " + name + " you adopted will greatly benefit from your generousity.";
            return View("ThankYou");
        }
        public ActionResult AnimalAdoptionForm()
        {
            return View();
        }
    }
}

MyChoice/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyChoice.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Save Our Species (SOS)";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Save Our Species (SOS)";

            return View();
        }
    }
}

MyChoice/Views/Animals/AnimalAdoptionForm.cshtml
@model MyChoice.Models.AnimalModel
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Animal Adoption Form</title>
    @Styles.Render("~/Content/Animal.css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <header>
        <h2>Animal Adoption Form</h2>
    </header>
    <form name="adoption" method="post">
        <p>
            Select the level of endangerment from the list:
            <select name="level" id="level">
                <option value="critical">Critical</option>
                <option value="endangered">Endangered</option>
                <option value="near threatened">Near Threatened</option>
                <option value="vulnerable">Vulnerable</option>
                <option value="least threatened">Least Threatened</option>
            </select>
        <p>Animal Name: <input type="text" name="name" id="name" /></p>
        <p>Donation:<input type="text" value="$100.00" name="donation" id="donation" />
        <p>Your Name: <input type="text" name="name" id="name" /></p>
        <p>Payment Method:
            <select name="payment">
                <option value="paypal">PayPal</option>
                <option value="visa">Visa</option>
                <option value="mastercard">MasterCard</option>
                <option value="check">Check</option>
                <option value="moneyorder">Money Order</option>
            </select>
        <button type="submit">Submit</button>
        </p>
    </form>
    <article>
        <a href="https://www.worldwildlife.org/species/amur-leopard">
            <div>
                <img src="~/Content/leopard.jpg" alt="leopard" style="height:200px;">
                <header>
                    <h2>Amur Leopard</h2>
                </header>
            </div>
        </a>
        <a href="https://www.worldwildlife.org/species/black-rhino">
            <div>
                <img src="~/Content/rhino.jpg" alt="rhino" style="height:200px;">
                <header>
                    <h2>Black Rhino</h2>
                </header>
            </div>
        </a>
        <a href="https://www.worldwildlife.org/species/bornean-orangutan">
            <div>
                <img src="~/Content/bornean.jpg" alt="bornean" style="height:200px;">
                <header>
                    <h2>Bornean Orangutan</h2>
                </header>
            </div>
        </a>
        <a href="https://www.worldwildlife.org/species/malayan-tiger">
            <div>
                <img src="~/Content/malaysian-tiger.jpg" alt="Malayan Tiger" style="height:200px;">
                <header>
                    <h2>Malayan Tiger</h2>
                </header>
            </div>
        </a>
        <a href="https://www.worldwildlife.org/species/orangutan">
            <div>
                <img src="~/Content/orangutan.jpg" alt="Orangutan" style="height:200px;">
                <header>
                    <h2>Orangutan</h2>
                </header>
            </div>
        </a>
        <a href="https://www.worldwildlife.org/species/sumatran-elephant">
            <div>
                <img src="~/Content/elephant.jpg" alt="Sumatran Elephant" style="height:200px;">
                <header>
                    <h2>Sumatran Elephant</h2>
                </header>
            </div>
        </a>
        <a href="https://www.worldwildlife.org/species/sumatran-tiger">
            <div>
                <img src="~/Content/sumatran-tiger.jpg" alt="Sumatran Tiger" style="height:200px;">
                <header>
                    <h2>Sumatran Tiger</h2>
                </header>
            </div>
        </a>
        <a href="https://www.worldwildlife.org/species/african-wild-dog">
            <div>
                <img src="~/Content/african-wild-dog.jpg" alt="African Wild Dog" style="height:200px;">
                <header>
                    <h2>African Wild Dog</h2>
                </header>
            </div>
        </a>
        <a href="https://www.worldwildlife.org/species/yangtze-finless-porpoise">
            <div>
                <img src="~/Content/porpoise.jpg" alt="Finless Porpoise" style="height:200px;">
                <header>
                    <h2>Yangtze Finless Porpoise</h2>
                </header>
            </div>
        </a>
        <a href="https://www.worldwildlife.org/species/sumatran-rhino#">
            <div>
                <img src="~/Content/rhino2.jpg" alt="Sumatran Rhino" style="height:200px;">
                <header>
                    <h2>Sumatran Rhino</h2>
                </header>
            </div>
        </a>
        <a href="https://www.worldwildlife.org/species/black-footed-ferret">
            <div>
                <img src="~/Content/ferret.jpg" alt="Black Footed Ferret" style="height:200px;">
                <header>
                    <h2>Black Footed Ferret</h2>
                </header>
            </div>
        </a>
        <a href="https://www.worldwildlife.org/species/blue-whale">
            <div>
                <img src="~/Content/blue-whale.jpg" alt="whale" style="height:200px;">
                <header>
                    <h2>Blue Whale</h2>
                </header>
            </div>
        </a>
        <a href="https://www.worldwildlife.org/species/cross-river-gorilla">
            <div>
                <img src="~/Content/gorilla.jpg" alt="gorilla" style="height:200px;">
                <header>
                    <h2>Cross River Gorilla</h2>
                </header>
            </div>
        </a>
        <a href="https://www.worldwildlife.org/species/hawksbill-turtle">
            <div>
                <img src="~/Content/turtle.jpg" alt="Hawksbill Turtle" style="height:200px;">
                <header>
                    <h2>Hawksbill Turtle</h2>
                </header>
            </div>
        </a>
    </article>

</body>
</html>

MyChoice/Views/Animals/Critical.cshtml
@{
    ViewBag.Title = "Critical";
}

<h2>Critical</h2>

MyChoice/Views/Animals/Endangered.cshtml
@{
    ViewBag.Title = "Endangered";
}

<h2>Endangered</h2>

MyChoice/Views/Animals/Index.cshtml
@{
    ViewBag.Title = "Animal Information";
}

<h2>What type of endangered animals would you like to learn more about?</h2>
<form name="endangeredSpecies" method="post">
    <select name="selCategory">
        <option name="critical">Critical</option>
        <option name="endangered">Endangered</option>
        <option name="nearthreatened">Near Threatened</option>
        <option name="vulnerable">Vulnerable</option>
        <option name="normal">Not Threatened</option>
    </select>
    <button type="submit">Submit</button>
</form>

MyChoice/Views/Animals/LeastThreatened.cshtml
@{
    ViewBag.Title = "Least Threatened";
}

<h2>Least Threatened</h2>

MyChoice/Views/Animals/NearThreatened.cshtml
@{
    ViewBag.Title = "Near Threatened";
}

<h2>Near Threatened</h2>

MyChoice/Views/Animals/ThankYou.cshtml
@{
    ViewBag.Title = "Thank You";
}

<h2>Thank You</h2>
@ViewBag.Message

MyChoice/Views/Animals/Vulnerable.cshtml
@{
    ViewBag.Title = "Vulnerable";
}

<h2>Vulnerable</h2>

MyChoice/Views/Home/About.cshtml
@{
    ViewBag.Title = "Save Our Species";
}
<h3>@ViewBag.Message</h3>

<p>Save Our Species is a non-profit organization dedicated to saving animals that are endangered and saving our planet</p>

MyChoice/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "SOS Contact";
}
<h3>@ViewBag.Message</h3>

<address>
   100 We Are the World Avenue<br />
    Traverse City, MI 49696<br />
    <abbr title="Phone">P:</abbr>
    800.555.1234
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@sos.com">Support@sos.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@sos.com">Marketing@sos.com</a>
</address>

MyChoice/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron" style="text-align:center;color:white;background-color:darkgreen;">
    <h1>Welcome to the Endangered Animals Support Site</h1>
</div>
<div style="text-align:center;">
    <a href="~/Content/sumatran-tiger.jpg" target="_blank"><img src="~/Content/sumatran-tiger.jpg" style="margin-right:50px;height:200px; outline:groove 10px black;" /></a>
    <a href="~/Content/leopard.jpg" target="_blank"><img src="~/Content/leopard.jpg" style="margin-right:50px;height:200px; outline:groove 10px black;" /></a>
    <a href="~/Content/elephant.jpg" target="_blank"><img src="~/Content/elephant.jpg" style="margin-right:50px;height:200px; outline:groove 10px black;" /></a>
</div>

MyChoice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Save Our Species</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Save Our Species", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Animal donation", "AnimalAdoptionForm", "Animals")</li>
                    <li>@Html.ActionLink("Animal Information", "Index", "Animals")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p style="text-align:right;">&copy; @DateTime.Now.Year - Save Our Species <img src="~/Content/paw.svg" style="width:20px;" /></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>